// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_food_to_consume : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_food_to_consume));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091123131_add_food_to_consume"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
