// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_delete_field_ingredients_and_units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_delete_field_ingredients_and_units));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021028122_add_delete_field_ingredients_and_units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
