// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_customer_and_food : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_customer_and_food));
        
        string IMigrationMetadata.Id
        {
            get { return "202105260928318_add_customer_and_food"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
