// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_Is_Serving_In_Saloon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Is_Serving_In_Saloon));
        
        string IMigrationMetadata.Id
        {
            get { return "202203271041299_add_Is_Serving_In_Saloon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
