// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_user_registerID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_user_registerID));
        
        string IMigrationMetadata.Id
        {
            get { return "202203280951211_remove_user_registerID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
